"""Add Pick model

Revision ID: 137dfaf12b94
Revises: fa815c63b09c
Create Date: 2025-08-02 05:42:56.427622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137dfaf12b94'
down_revision = 'fa815c63b09c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('event_details', sa.String(length=200), nullable=False),
    sa.Column('pick_selection', sa.String(length=100), nullable=False),
    sa.Column('stake_units', sa.Integer(), nullable=False),
    sa.Column('odds', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('date_posted', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('picks')
    # ### end Alembic commands ###
