"""Add favorite_team, avatar_url to User and add Post model

Revision ID: 273adc9becda
Revises: adc4f6d89615
Create Date: 2025-08-02 08:21:56.938257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273adc9becda'
down_revision = 'adc4f6d89615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_team', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('favorite_team')

    op.drop_table('posts')
    # ### end Alembic commands ###
