"""Add email_private and is_admin to User model

Revision ID: 84257da0798d
Revises: 8d9468318498
Create Date: 2025-08-02 07:47:10.425989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84257da0798d'
down_revision = '8d9468318498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_private', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('email_private')

    # ### end Alembic commands ###
