"""Add grading fields to Pick model

Revision ID: cf1d66abc170
Revises: 273adc9becda
Create Date: 2025-08-02 12:50:52.077296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1d66abc170'
down_revision = '273adc9becda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('result', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('graded_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('graded_odds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('final_score', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.drop_column('final_score')
        batch_op.drop_column('graded_odds')
        batch_op.drop_column('graded_timestamp')
        batch_op.drop_column('result')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
