"""Create pending_picks and graded_picks tables

Revision ID: eb470fc9e02e
Revises: ce69638b0e1f
Create Date: 2025-08-05 02:04:13.097744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb470fc9e02e'
down_revision = 'ce69638b0e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graded_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('event_details', sa.String(length=200), nullable=False),
    sa.Column('pick_selection', sa.String(length=100), nullable=False),
    sa.Column('stake_units', sa.Float(), nullable=False),
    sa.Column('odds', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('graded_timestamp', sa.DateTime(), nullable=True),
    sa.Column('graded_odds', sa.Integer(), nullable=True),
    sa.Column('final_score', sa.String(length=50), nullable=True),
    sa.Column('bet_type', sa.String(length=20), nullable=True),
    sa.Column('potential_win', sa.Float(), nullable=True),
    sa.Column('api_event_id', sa.String(length=100), nullable=True),
    sa.Column('market_key', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('event_details', sa.String(length=200), nullable=False),
    sa.Column('pick_selection', sa.String(length=100), nullable=False),
    sa.Column('stake_units', sa.Float(), nullable=False),
    sa.Column('odds', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bet_type', sa.String(length=20), nullable=True),
    sa.Column('potential_win', sa.Float(), nullable=True),
    sa.Column('api_event_id', sa.String(length=100), nullable=True),
    sa.Column('market_key', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('picks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sport', sa.VARCHAR(length=50), nullable=False),
    sa.Column('event_details', sa.VARCHAR(length=200), nullable=False),
    sa.Column('pick_selection', sa.VARCHAR(length=100), nullable=False),
    sa.Column('stake_units', sa.FLOAT(), nullable=False),
    sa.Column('odds', sa.INTEGER(), nullable=False),
    sa.Column('date_posted', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('result', sa.VARCHAR(length=20), nullable=True),
    sa.Column('graded_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('graded_odds', sa.INTEGER(), nullable=True),
    sa.Column('final_score', sa.VARCHAR(length=50), nullable=True),
    sa.Column('bet_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('potential_win', sa.FLOAT(), nullable=True),
    sa.Column('api_event_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('market_key', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pending_picks')
    op.drop_table('graded_picks')
    # ### end Alembic commands ###
