#!/usr/bin/env python3
"""Make the homepage atomic: HTML can never pair with a different build's CSS/JS.

GitHub Pages ignores query strings, so `?v=` cache-busting is a no-op: an
index.html cached in a visitor's browser (Cache-Control: max-age=600) will
happily load TODAY's bytes from `?v=<yesterday>`. Old markup + new CSS renders
as a broken page for as long as the stale document lives.

Two changes remove that failure mode entirely:

  1. The homepage's render-critical CSS is inlined into index.html. The design
     ships inside the document, so there is no second file to get out of sync
     and the first painted frame is always correct.
  2. The homepage JS is published under content-hashed, immutable filenames.
     A document can only ever request the exact bytes it was built against.
     Old hashed files are never deleted, so previously served documents keep
     resolving their own JS.

Run after editing static/css/tmr-home-v2.css or the homepage JS:
    python scripts/build_home_critical.py
Verify index.html is in sync (CI / pre-push guard):
    python scripts/build_home_critical.py --check
"""
import hashlib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
INDEX = ROOT / "index.html"
CRITICAL_CSS = ROOT / "static/css/tmr-home-v2.css"
# first-pick-onboarding.js is here because the homepage now depends on the
# document and that script agreeing: the early block at the top of <body> paints
# the reminder strip during parse, and this file adopts that node and wires its
# handlers. A stale copy from a `?v=` cache would leave the strip on screen with
# a dead dismiss button and would still tear it out on a failed status call --
# the exact layout shift the early block exists to prevent. The other 96 pages
# keep loading the unhashed file with `?v=` and are unaffected.
HASHED_JS = ["static/js/tmr-home-live.js", "static/js/first-pick-onboarding.js"]

CSS_BEGIN = "<!-- BEGIN HOME CRITICAL CSS - generated by scripts/build_home_critical.py, do not edit by hand -->"
CSS_END = "<!-- END HOME CRITICAL CSS -->"


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()[:12]


BUILD_STAMP_RE = re.compile(rb"var BUILD = '[^']*'")


def build(html):
    # 1. Inline the critical CSS, replacing either the <link> or a previous block.
    block = "%s\n<style>\n%s\n</style>\n%s" % (
        CSS_BEGIN, CRITICAL_CSS.read_text(encoding="utf-8").strip(), CSS_END)
    if CSS_BEGIN in html:
        html = re.sub(re.escape(CSS_BEGIN) + r".*?" + re.escape(CSS_END), lambda m: block,
                      html, flags=re.S)
    else:
        link = re.compile(r'[ \t]*<link[^>]+href="/static/css/tmr-home-v2\.css[^"]*"[^>]*>')
        if not link.search(html):
            sys.exit("index.html references neither the critical CSS link nor the generated block")
        html = link.sub(lambda m: block, html, count=1)

    # 2. Point every homepage script at an immutable, content-hashed twin.
    for rel in HASHED_JS:
        src = ROOT / rel
        stem, suffix = src.stem, src.suffix
        # Stamp the build id into the JS AND <html data-tmr-build> so the page
        # can detect a document/script pairing from two different deployments
        # (stale HTTP cache, restored session) and self-heal with one reload.
        # The digest is computed with the stamp masked so it stays stable.
        raw = src.read_bytes()
        masked = BUILD_STAMP_RE.sub(b"var BUILD = ''", raw)
        h = hashlib.sha256(masked).hexdigest()[:12]
        stamped = BUILD_STAMP_RE.sub(("var BUILD = '%s'" % h).encode(), raw)
        if stamped != raw:
            src.write_bytes(stamped)
        hashed = "%s.%s%s" % (stem, h, suffix)
        (src.parent / hashed).write_bytes(stamped)
        # Only the script that actually carries `var BUILD` owns the document's
        # build id -- that pairing is what its self-heal reload compares. Letting
        # a second hashed file overwrite the attribute would point the check at a
        # hash no script reports, and every load would look like a mismatch.
        if BUILD_STAMP_RE.search(raw):
            if 'data-tmr-build="' not in html:
                sys.exit("index.html is missing the data-tmr-build attribute on <html>")
            html = re.sub(r'data-tmr-build="[^"]*"', 'data-tmr-build="%s"' % h, html, count=1)
        pattern = re.compile(r'src="/%s/%s(\.[0-9a-f]{12})?%s(\?[^"]*)?"'
                             % (re.escape(str(src.parent.relative_to(ROOT)).replace("\\", "/")),
                                re.escape(stem), re.escape(suffix)))
        if not pattern.search(html):
            sys.exit("index.html does not reference %s" % rel)
        html = pattern.sub('src="/%s/%s"' % (str(src.parent.relative_to(ROOT)).replace("\\", "/"),
                                             hashed), html)
    return html


def main():
    current = INDEX.read_text(encoding="utf-8")
    built = build(current)
    if "--check" in sys.argv:
        if built != current:
            sys.exit("index.html is STALE - run: python scripts/build_home_critical.py")
        print("index.html is in sync with the homepage CSS/JS")
        return
    if built == current:
        print("index.html already up to date")
        return
    INDEX.write_text(built, encoding="utf-8")
    print("index.html rebuilt: critical CSS inlined, homepage JS pinned to content hashes")


if __name__ == "__main__":
    main()
