#!/usr/bin/env python3
"""Make the homepage atomic: HTML can never pair with a different build's CSS/JS.

GitHub Pages ignores query strings, so `?v=` cache-busting is a no-op: an
index.html cached in a visitor's browser (Cache-Control: max-age=600) will
happily load TODAY's bytes from `?v=<yesterday>`. Old markup + new CSS renders
as a broken page for as long as the stale document lives.

Two changes remove that failure mode entirely:

  1. The homepage's render-critical CSS is inlined into index.html. The design
     ships inside the document, so there is no second file to get out of sync
     and the first painted frame is always correct.
  2. The homepage JS is published under content-hashed, immutable filenames.
     A document can only ever request the exact bytes it was built against.
     Old hashed files are never deleted, so previously served documents keep
     resolving their own JS.

Run after editing static/css/tmr-home-v2.css or the homepage JS:
    python scripts/build_home_critical.py
Verify index.html is in sync (CI / pre-push guard):
    python scripts/build_home_critical.py --check
"""
import hashlib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
INDEX = ROOT / "index.html"
CRITICAL_CSS = ROOT / "static/css/tmr-home-v2.css"
HASHED_JS = ["static/js/tmr-home-auth.js", "static/js/tmr-home-live.js"]

CSS_BEGIN = "<!-- BEGIN HOME CRITICAL CSS - generated by scripts/build_home_critical.py, do not edit by hand -->"
CSS_END = "<!-- END HOME CRITICAL CSS -->"


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()[:12]


def build(html):
    # 1. Inline the critical CSS, replacing either the <link> or a previous block.
    block = "%s\n<style>\n%s\n</style>\n%s" % (
        CSS_BEGIN, CRITICAL_CSS.read_text(encoding="utf-8").strip(), CSS_END)
    if CSS_BEGIN in html:
        html = re.sub(re.escape(CSS_BEGIN) + r".*?" + re.escape(CSS_END), lambda m: block,
                      html, flags=re.S)
    else:
        link = re.compile(r'[ \t]*<link[^>]+href="/static/css/tmr-home-v2\.css[^"]*"[^>]*>')
        if not link.search(html):
            sys.exit("index.html references neither the critical CSS link nor the generated block")
        html = link.sub(lambda m: block, html, count=1)

    # 2. Point every homepage script at an immutable, content-hashed twin.
    for rel in HASHED_JS:
        src = ROOT / rel
        stem, suffix = src.stem, src.suffix
        hashed = "%s.%s%s" % (stem, digest(src), suffix)
        (src.parent / hashed).write_bytes(src.read_bytes())
        pattern = re.compile(r'src="/%s/%s(\.[0-9a-f]{12})?%s(\?[^"]*)?"'
                             % (re.escape(str(src.parent.relative_to(ROOT)).replace("\\", "/")),
                                re.escape(stem), re.escape(suffix)))
        if not pattern.search(html):
            sys.exit("index.html does not reference %s" % rel)
        html = pattern.sub('src="/%s/%s"' % (str(src.parent.relative_to(ROOT)).replace("\\", "/"),
                                             hashed), html)
    return html


def main():
    current = INDEX.read_text(encoding="utf-8")
    built = build(current)
    if "--check" in sys.argv:
        if built != current:
            sys.exit("index.html is STALE - run: python scripts/build_home_critical.py")
        print("index.html is in sync with the homepage CSS/JS")
        return
    if built == current:
        print("index.html already up to date")
        return
    INDEX.write_text(built, encoding="utf-8")
    print("index.html rebuilt: critical CSS inlined, homepage JS pinned to content hashes")


if __name__ == "__main__":
    main()
