"""PROFILE_EXPLORER_20260926: copy the profile's own .tmrx component styles into
static/css/tmr-profile-tmrx.css so pages outside /profile/ (the team page,
/profile/team/) render tables, ribbons, pills and sections in exactly the
profile's style. Source of truth stays profile/index.html; rerun after
editing any .tmrx rule there:  python scripts/build_profile_tmrx_css.py"""
import re, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
html = (ROOT / 'profile' / 'index.html').read_text(encoding='utf-8')
css = '\n'.join(re.findall(r'<style[^>]*>(.*?)</style>', html, flags=re.S))
css = re.sub(r'/\*.*?\*/', '', css, flags=re.S)

def blocks(text):
    i, n, out = 0, len(text), []
    while i < n:
        j = text.find('{', i)
        if j < 0: break
        sel = text[i:j].strip()
        depth, k = 1, j + 1
        while k < n and depth:
            if text[k] == '{': depth += 1
            elif text[k] == '}': depth -= 1
            k += 1
        out.append((sel, text[j + 1:k - 1]))
        i = k
    return out

def keep(text):
    out = []
    for sel, body in blocks(text):
        if sel.startswith('@media') or sel.startswith('@supports'):
            inner = keep(body)
            if inner: out.append(sel + ' {\n' + inner + '\n}')
        elif sel.startswith('@'):
            continue
        else:
            parts = [s.strip() for s in sel.split(',') if 'tmrx' in s]
            # rules scoped to the profile body keep working: the team page carries the same body classes
            if parts: out.append(', '.join(parts) + ' {' + body.strip() + '}')
    return '\n'.join(out)

result = keep(css)
header = '/* GENERATED by scripts/build_profile_tmrx_css.py from profile/index.html. Do not edit. */\n'
(ROOT / 'static' / 'css' / 'tmr-profile-tmrx.css').write_text(header + result + '\n', encoding='utf-8')
print(len(result.splitlines()), 'rules')
